/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab03.ui;

import lab03.util.GerenciadorDeResultados;

/**
 * 
 * @author Fagner
 */
public class TabelaDeResultados extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1694051409432898226L;
	/**
	 * Creates new form TabelaDeResultados
	 */
	public TabelaDeResultados() {
		initComponents();
	}

	public TabelaDeResultados(String filePath) {
		initComponents();
		diretorio.setText(filePath);
		resultado.setEnabled(false);
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">

	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		barraDeProgresso = new javax.swing.JProgressBar();
		barraDeProgresso.setValue(0);
		barraDeProgresso.setStringPainted(true);
		encontrados = new javax.swing.JLabel();
		numArquivosParcial = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		numArquivosTotal = new javax.swing.JLabel();
		porcentagen = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		resultado = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		diretorio = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		encontrados.setText("nenhuma referencia encontrada");

		numArquivosParcial
				.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		numArquivosParcial.setText("0");

		jLabel2.setText("de");

		numArquivosTotal.setText("0 arquivo");

		porcentagen.setText("");

		resultado.setModel(new TabelaUi());
//				new javax.swing.table.DefaultTableModel(
//				new Object[][] {},
//				new String[] { "Palavra Chave", "Frequência" }) {
//			/**
//			 * 
//			 */
//			private static final long serialVersionUID = 7584618057417700327L;
//			@SuppressWarnings("rawtypes")
//			Class[] types = new Class[] { java.lang.String.class,
//					java.lang.Integer.class };
//			boolean[] canEdit = new boolean[] { true, false };
//
//			@SuppressWarnings({ "rawtypes", "unchecked" })
//			public Class getColumnClass(int columnIndex) {
//				return types[columnIndex];
//			}
//
//			public boolean isCellEditable(int rowIndex, int columnIndex) {
//				return canEdit[columnIndex];
//			}
//		});
		jScrollPane2.setViewportView(resultado);

		jLabel1.setText("Diretorio:");

		diretorio.setText("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				encontrados)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				numArquivosParcial,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				23,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				numArquivosTotal,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				77,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				barraDeProgresso,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				porcentagen)
																		.addGap(12,
																				12,
																				12))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				diretorio,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												391, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(diretorio))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																barraDeProgresso,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				encontrados)
																		.addComponent(
																				numArquivosParcial)
																		.addComponent(
																				jLabel2)
																		.addComponent(
																				numArquivosTotal))
														.addComponent(
																porcentagen))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					TabelaDeResultados.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TabelaDeResultados().setVisible(true);
			}
		});
	}

	static public synchronized void  updateNumArquivo() {
		int num = GerenciadorDeResultados.getCurrentInstance()
					.getNumTotalArquivos();
			String texto = num + " arquivos";
			switch (num) {
			case 0:
				texto = "0 arquivos";
				break;
			case 1:
				texto = "1 arquivo";
				break;
			}

			numArquivosTotal.setText(texto);
			barraDeProgresso.setMaximum(num);
		
	}

	static public synchronized void updateTable() {
			GerenciadorDeResultados gResultado = GerenciadorDeResultados
					.getCurrentInstance();
			if (gResultado.temModificacao()) {
				numArquivosParcial.setText(gResultado.getArquivosPesquisados()
						+ "");
				encontrados.setText(gResultado.getTotalEncontrado()
						+ " palavras chaves em ");
				numTotal = gResultado.getArquivosPesquisados();
				barraDeProgresso.setValue(numTotal);
				numArquivosTotal.setText(numTotal + " arquivos em "
						+ gResultado.getTempoDecorrido() + " milisegundos");
				resultado.setModel(new TabelaUi(gResultado.getResultado()));
				try {
					Thread.sleep(200);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		

	}

	// Variables declaration - do not modify

	private static int numTotal = 0;
	private static javax.swing.JProgressBar barraDeProgresso;
	private javax.swing.JLabel diretorio;
	private static javax.swing.JLabel encontrados;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private static javax.swing.JLabel numArquivosParcial;
	private static javax.swing.JLabel numArquivosTotal;
	private javax.swing.JLabel porcentagen;
	private static javax.swing.JTable resultado;
	// End of variables declaration
}
