/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab03.ui;

import java.awt.event.ActionEvent;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import javax.swing.JOptionPane;

import lab03.runnable.Leitor;

/**
 * 
 * @author Fagner
 */
public class TelaInicial extends javax.swing.JFrame {

	/**
	 * 
	 */
	

	/**
	 * Creates new form TelaInicial
	 * @param listadorDeArquivos 
	 */
	public TelaInicial() {
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		folderPath = new javax.swing.JLabel();
		numThreads = new javax.swing.JFormattedTextField(
				java.text.NumberFormat.getInstance());
		jLabel5 = new javax.swing.JLabel();
		abrirPasta = new javax.swing.JButton();
		IniciarPesquisa = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Si1 2012.2");

		jLabel2.setText("Pasta:");

		jLabel3.setText("Threads");

		folderPath.setText("Nenhuma pasta Selecionada");

		numThreads.setText("0");

		jLabel5.setText("(o para ilimitada)");

		abrirPasta.setText("Abrir");
		abrirPasta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				abrirPastaActionPerformed(evt);
			}
		});

		IniciarPesquisa.setText("Iniciar");
		IniciarPesquisa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				IniciarPesquisaActionPerformed(evt);
			}

		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				folderPath)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				146,
																				Short.MAX_VALUE)
																		.addComponent(
																				abrirPasta))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												numThreads,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												50,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel5)))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				IniciarPesquisa)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																folderPath)
														.addComponent(
																abrirPasta))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																numThreads,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addGap(7, 7, 7)
										.addComponent(IniciarPesquisa)
										.addContainerGap(21, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	protected void IniciarPesquisaActionPerformed(ActionEvent evt) {
		String err = "";
		if (folderPath.getText().equals("Nenhuma pasta Selecionada")) {
			err = "Selecione uma Pasta";
			}
		try {
			int i = Integer.parseInt(numThreads.getText());
			if (i <0) err = "Digite um Numero Positivo";
		} catch (NumberFormatException e) {
			err = "Numero Invalido";
			e.hashCode();
		}
		if (!err.equals("")) {
			JOptionPane.showMessageDialog(this, err, "Erro", JOptionPane.ERROR_MESSAGE);
		}
		else
		{
		this.dispose();
		int numMax = Integer.parseInt(numThreads.getText());
		if (numMax<1) numMax = Integer.MAX_VALUE;
		ExecutorService executor = new ThreadPoolExecutor(numMax, numMax, 1, TimeUnit.MILLISECONDS, new LinkedBlockingDeque<Runnable>());
		executor.execute(new Leitor(executor, folderPath.getText()));
		telaResultados = new TabelaDeResultados(folderPath.getText());
		telaResultados.setSize(800, 600);
		
		telaResultados.setVisible(true);
		}
	
	}

	private void abrirPastaActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
		chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
			folderPath.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaInicial().setVisible(true);
			}
		});
	}
	public TabelaDeResultados getTelaResultados() {
		return telaResultados;
	}
	// Variables declaration - do not modify

	private static final long serialVersionUID = -1312068541826905502L;
	private TabelaDeResultados telaResultados;
	private javax.swing.JButton IniciarPesquisa;
	private javax.swing.JButton abrirPasta;
	private javax.swing.JLabel folderPath;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JFormattedTextField numThreads;
	// End of variables declaration
}
